version: 2.1
orbs:
  release-management: salesforce/npm-release-management@4
  slack: circleci/slack@4.4.4

workflows:
  version: 2
  test-and-release:
    jobs:
      - release-management/validate-pr:
          filters:
            branches:
              ignore: main
      - release-management/test-package:
          matrix:
            parameters:
              os:
                - linux
              node_version:
                - latest
                - lts
                - maintenance
      - release-management/release-package:
          github-release: false
          tag: pubtest
          prerelease: true
          post-job-steps:
            - run: yarn ci-docs
            - slack/notify:
                channel: 'cli-team-notifications'
                custom: |
                  {
                    "blocks": [
                      {
                        "type": "section",
                        "fields": [
                          {
                            "type": "plain_text",
                            "text":  "SDR Library v${RELEASE_VERSION} has been published to npm"
                          }
                        ]
                      }
                    ]
                  }
                event: pass
          requires:
            - release-management/test-package
            # - external-nut
          filters:
            branches:
              only: sm/publish-via-orb
              # only: main
          context: CLI_CTC
